<a href="https://colab.research.google.com/github/yeesem/Natural-Laguage-Processing/blob/main/Latent_Dirichlet_Allocation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
import pandas as pd

In [42]:
npr = pd.read_csv("https://raw.githubusercontent.com/yeesem/NLP_Dataset/main/npr.csv",engine="python",error_bad_lines=False,encoding='utf-8')

<ipython-input-42-02b1402179c7>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  npr = pd.read_csv("https://raw.githubusercontent.com/yeesem/NLP_Dataset/main/npr.csv",engine="python",error_bad_lines=False,encoding='utf-8')
Skipping line 1176: unexpected end of data


In [35]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [38]:
npr['Article'][0]

'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

In [39]:
len(npr)

1174

In [43]:
from sklearn.feature_extraction.text import CountVectorizer

In [44]:
cv = CountVectorizer(max_df = 0.9,min_df = 2,stop_words = 'english')

In [45]:
dtm = cv.fit_transform(npr['Article'])

In [46]:
dtm

<1174x17960 sparse matrix of type '<class 'numpy.int64'>'
	with 279649 stored elements in Compressed Sparse Row format>

In [49]:
from sklearn.decomposition import LatentDirichletAllocation

In [51]:
LDA = LatentDirichletAllocation(n_components=7,random_state = 42)

In [52]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [62]:
#Grab the vocabulary of words
len(cv.get_feature_names_out())

17960

In [66]:
type(cv.get_feature_names_out())

numpy.ndarray

In [67]:
cv.get_feature_names_out()[1000]

'announces'

In [70]:
import random

random_word_id = random.randint(0,17960)

print(random_word_id)
print(cv.get_feature_names_out()[random_word_id])

11260
operators


In [71]:
len(LDA.components_)

7

In [73]:
type(LDA.components_)

numpy.ndarray

In [75]:
LDA.components_.shape

(7, 17960)

In [76]:
LDA.components_

array([[2.83443004e+00, 1.63702101e+02, 1.42857146e-01, ...,
        2.14254361e+00, 7.81410487e+00, 1.42857143e-01],
       [1.45091207e-01, 2.21811040e+01, 1.42913557e-01, ...,
        1.42857144e-01, 1.43412406e-01, 1.42857143e-01],
       [1.43030131e-01, 2.05679177e+02, 1.42871196e-01, ...,
        1.42883402e-01, 1.43654758e-01, 2.14285714e+00],
       ...,
       [1.42857151e-01, 1.43552945e+01, 3.14245781e+00, ...,
        1.42857145e-01, 1.42907865e-01, 1.42857143e-01],
       [1.42857147e-01, 4.48718457e+01, 1.42913393e-01, ...,
        1.42949018e-01, 1.29091310e+00, 1.42857143e-01],
       [1.46197527e-01, 4.26197053e+01, 1.43126255e-01, ...,
        1.43052535e-01, 1.43384541e-01, 1.42857143e-01]])

In [77]:
single_topic = LDA.components_[0]

In [78]:
single_topic.argsort()

array([ 1216, 17546, 17578, ..., 14051, 11784, 14157])

In [79]:
#Demostration of argsort()
import numpy as np

In [80]:
arr = np.array([10,200,1])

In [81]:
arr

array([ 10, 200,   1])

In [82]:
#Sort the array and return the ascending order in index form
arr.argsort()

array([2, 0, 1])

In [83]:
#ARGSORT - INDEX POSITIONS SORTED FROM LEAST ---> GREATEST
#TOP 1- VALUES (10 GREATEST VALUES)
#LAST 10 VALUES OF ARGSORT()
single_topic.argsort()[-10:]

array([15340,  9475, 17658,  8923, 10879, 16693, 17773, 14051, 11784,
       14157])

In [84]:
top_ten_word = single_topic.argsort()[-10:]

In [86]:
for index in top_ten_word:
  print(cv.get_feature_names_out()[index])

state
like
white
just
new
trump
women
said
people
says


In [87]:
top_twenty_word = single_topic.argsort()[-20:]

In [89]:
for index in top_twenty_word:
  print(cv.get_feature_names_out()[index])

years
according
told
time
news
facebook
npr
000
march
senate
state
like
white
just
new
trump
women
said
people
says


In [91]:
for index,topic in enumerate(LDA.components_):
  print(f"THE TOP 15 WORDS FOR TOPIC #{index}")
  print([cv.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
  print('\n')
  print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['facebook', 'npr', '000', 'march', 'senate', 'state', 'like', 'white', 'just', 'new', 'trump', 'women', 'said', 'people', 'says']




THE TOP 15 WORDS FOR TOPIC #1
['npr', 'military', 'american', 'told', 'country', 'says', 'killed', 'white', 'house', 'attack', 'new', 'people', 'said', 'president', 'trump']




THE TOP 15 WORDS FOR TOPIC #2
['000', 'states', 'patients', 'money', 'new', 'law', 'federal', 'drug', 'percent', 'insurance', 'said', 'people', 'says', 'care', 'health']




THE TOP 15 WORDS FOR TOPIC #3
['executive', 'department', 'federal', 'court', 'russia', 'government', 'new', 'people', 'order', 'administration', 'house', 'obama', 'president', 'said', 'trump']




THE TOP 15 WORDS FOR TOPIC #4
['food', 'time', 'world', 'scientists', 'winner', 'just', 'years', 'year', 'song', 'best', 'like', 'album', 'new', 'music', 'says']




THE TOP 15 WORDS FOR TOPIC #5
['work', 'life', 'new', 'black', 'way', 'years', 'don', 'know', 'students', 'time', 'scho

In [92]:
dtm

<1174x17960 sparse matrix of type '<class 'numpy.int64'>'
	with 279649 stored elements in Compressed Sparse Row format>

In [93]:
npr

Article
0     In the Washington of 2016, even when the polic...
1       Donald Trump has used Twitter  —   his prefe...
2       Donald Trump is unabashedly praising Russian...
3     Updated at 2:50 p. m. ET, Russian President Vl...
4     From photography, illustration and video, to d...
...                                                 ...
1169  Two decades ago only about 9 percent of childr...
1170  Royal Canadian Mounted Police are reporting a ...
1171  The young mother spoke softly but with determi...
1172  One of the most joyful shows I’ve heard in yea...
1173  The first sign of trouble was the monkeys drop...

[1174 rows x 1 columns]

In [94]:
topic_result = LDA.transform(dtm)

In [95]:
topic_result

array([[2.28212251e-04, 2.28382447e-04, 2.28304708e-04, ...,
        2.28024923e-04, 2.28309472e-04, 2.28270946e-04],
       [1.91344068e-01, 4.49751646e-04, 4.48997195e-04, ...,
        4.48610022e-04, 4.49372774e-04, 4.49007916e-04],
       [3.31505013e-04, 3.30974844e-04, 3.30516151e-04, ...,
        3.30634354e-04, 3.30806262e-04, 3.30714577e-04],
       ...,
       [1.79649277e-01, 4.08633924e-04, 2.02862939e-02, ...,
        4.08049020e-04, 3.29419990e-01, 4.08572382e-04],
       [1.22384677e-01, 1.12005133e-03, 1.11866685e-03, ...,
        5.57099067e-01, 2.53487842e-01, 6.36688023e-02],
       [3.39819515e-04, 3.39577325e-04, 9.09968978e-01, ...,
        8.83323880e-02, 3.39889473e-04, 3.39885509e-04]])

In [96]:
topic_result.shape

(1174, 7)

In [99]:
topic_result[0].shape

(7,)

In [103]:
#Return the index position of highest probability
topic_result[0].argmax()

3

In [104]:
npr['Topic'] = topic_result.argmax(axis = 1)