<a href="https://colab.research.google.com/github/yeesem/Natural-Laguage-Processing/blob/main/Non_Negative_Matrix_Factorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [6]:
npr = pd.read_csv('https://raw.githubusercontent.com/yeesem/NLP_Dataset/main/npr.csv',engine = 'python',error_bad_lines = False)

<ipython-input-6-53d4942f8971>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  npr = pd.read_csv('https://raw.githubusercontent.com/yeesem/NLP_Dataset/main/npr.csv',engine = 'python',error_bad_lines = False)
Skipping line 1176: unexpected end of data


In [7]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
tfidf = TfidfVectorizer(max_df = 0.95,min_df = 2,stop_words = 'english')

In [10]:
dtm = tfidf.fit_transform(npr['Article'])

In [11]:
dtm

<1174x17960 sparse matrix of type '<class 'numpy.float64'>'
	with 279649 stored elements in Compressed Sparse Row format>

In [12]:
from sklearn.decomposition import NMF

In [13]:
nmf_model = NMF(n_components = 7,random_state = 42)

In [14]:
nmf_model.fit(dtm)

NMF(n_components=7, random_state=42)

In [16]:
tfidf.get_feature_names_out()[200]

'28th'

In [17]:
len(tfidf.get_feature_names_out())

17960

In [18]:
nmf_model.components_

array([[4.60753339e-03, 4.56536420e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 6.98309239e-02, 3.38529823e-03, ...,
        1.40343145e-03, 3.77181592e-03, 2.19144717e-04],
       [2.48937064e-04, 6.19593071e-02, 0.00000000e+00, ...,
        0.00000000e+00, 6.43165892e-05, 8.95734447e-04],
       ...,
       [0.00000000e+00, 0.00000000e+00, 1.79710121e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.90168015e-03, 8.91141318e-03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.24785940e-05],
       [0.00000000e+00, 4.34589910e-02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [19]:
nmf_model.components_.shape

(7, 17960)

In [20]:
for index,topic in enumerate(nmf_model.components_):
  print(f"THE TOP 15 WORD FOR TOPIC #{index}")
  print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
  print('\n\n')

THE TOP 15 WORD FOR TOPIC #0
['trade', 'business', 'administration', 'campaign', 'ethics', 'donald', 'office', 'inauguration', 'hotel', 'obama', 'house', 'white', 'said', 'president', 'trump']



THE TOP 15 WORD FOR TOPIC #1
['think', 'way', 'year', 'music', 'world', 'life', 'years', 'really', 'women', 'time', 'new', 'just', 'people', 'like', 'says']



THE TOP 15 WORD FOR TOPIC #2
['said', 'aca', 'plans', 'republicans', 'plan', 'people', 'affordable', 'medicaid', 'repeal', 'law', 'obamacare', 'coverage', 'care', 'insurance', 'health']



THE TOP 15 WORD FOR TOPIC #3
['states', 'seven', 'refugee', 'judge', 'said', 'immigration', 'department', 'travel', 'president', 'countries', 'court', 'refugees', 'executive', 'ban', 'order']



THE TOP 15 WORD FOR TOPIC #4
['cabinet', 'gorsuch', 'court', 'trump', 'vote', 'confirmation', 'republicans', 'nomination', 'sen', 'nominee', 'nominees', 'committee', 'sessions', 'democrats', 'senate']



THE TOP 15 WORD FOR TOPIC #5
['tillerson', 'reports', 'k

In [26]:
topic_results = nmf_model.transform(dtm)

In [27]:
topic_results

array([[0.05742891, 0.        , 0.0020617 , ..., 0.03225941, 0.33561912,
        0.00272323],
       [0.15547513, 0.00140874, 0.        , ..., 0.        , 0.02698126,
        0.        ],
       [0.091985  , 0.        , 0.        , ..., 0.00841165, 0.30362303,
        0.        ],
       ...,
       [0.        , 0.05553731, 0.0300902 , ..., 0.        , 0.13054365,
        0.01287971],
       [0.        , 0.0600452 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.05594259, 0.04410935, ..., 0.        , 0.        ,
        0.0025654 ]])

In [28]:
topic_results[0]

array([0.05742891, 0.        , 0.0020617 , 0.        , 0.03225941,
       0.33561912, 0.00272323])

In [29]:
#Index for topic position
topic_results[0].argmax()

5

In [30]:
topic_results.argmax(axis = 1)

array([5, 0, 5, ..., 5, 1, 1])

In [31]:
npr['Topic'] = topic_results.argmax(axis = 1)

In [32]:
npr.head()

Article  Topic
0  In the Washington of 2016, even when the polic...      5
1    Donald Trump has used Twitter  —   his prefe...      0
2    Donald Trump is unabashedly praising Russian...      5
3  Updated at 2:50 p. m. ET, Russian President Vl...      5
4  From photography, illustration and video, to d...      1

In [33]:
npr.tail()

Article  Topic
1169  Two decades ago only about 9 percent of childr...      1
1170  Royal Canadian Mounted Police are reporting a ...      1
1171  The young mother spoke softly but with determi...      5
1172  One of the most joyful shows I’ve heard in yea...      1
1173  The first sign of trouble was the monkeys drop...      1

In [35]:
npr['Topic'].value_counts()

1    646
0    155
3    126
2     71
5     68
4     65
6     43
Name: Topic, dtype: int64

In [41]:
#Running time is greater than the LDA
#Assignment of topic is based on the domain knowledge
topic_dict = {0:'Election',1:'Music',2:'Health',3:'Legis',4:'Politics',5:'Politics',6:'Education'}
npr['Topic Label'] = npr['Topic'].map(topic_dict)

In [42]:
npr.head()

Article  Topic Topic Label
0  In the Washington of 2016, even when the polic...      5    Politics
1    Donald Trump has used Twitter  —   his prefe...      0    Election
2    Donald Trump is unabashedly praising Russian...      5    Politics
3  Updated at 2:50 p. m. ET, Russian President Vl...      5    Politics
4  From photography, illustration and video, to d...      1       Music

In [43]:
npr.tail()

Article  Topic Topic Label
1169  Two decades ago only about 9 percent of childr...      1       Music
1170  Royal Canadian Mounted Police are reporting a ...      1       Music
1171  The young mother spoke softly but with determi...      5    Politics
1172  One of the most joyful shows I’ve heard in yea...      1       Music
1173  The first sign of trouble was the monkeys drop...      1       Music