<a href="https://colab.research.google.com/github/yeesem/Natural-Laguage-Processing/blob/main/Text_Generation_with_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
#Read file function
def read_file(filepath):
  with open(filepath) as f:
    str_text = f.read()

  return str_text

In [130]:
read_file("/content/moby_dick_four_chapters.txt")[:1000]

"Call me Ishmael.  Some years ago--never mind how long\nprecisely--having little or no money in my purse, and nothing\nparticular to interest me on shore, I thought I would sail about a\nlittle and see the watery part of the world.  It is a way I have of\ndriving off the spleen and regulating the circulation.  Whenever I\nfind myself growing grim about the mouth; whenever it is a damp,\ndrizzly November in my soul; whenever I find myself involuntarily\npausing before coffin warehouses, and bringing up the rear of every\nfuneral I meet; and especially whenever my hypos get such an upper\nhand of me, that it requires a strong moral principle to prevent me\nfrom deliberately stepping into the street, and methodically knocking\npeople's hats off--then, I account it high time to get to sea as soon\nas I can.  This is my substitute for pistol and ball.  With a\nphilosophical flourish Cato throws himself upon his sword; I quietly\ntake to the ship.  There is nothing surprising in this.  If th

In [76]:
import spacy

In [77]:
nlp = spacy.load('en_core_web_sm',disable = ['parser','tagger','ner'])

In [78]:
nlp_max_length = 1198623

In [79]:
def separate_punc(doc_text):
  return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [80]:
d = read_file('/content/moby_dick_four_chapters.txt')

In [81]:
tokens = separate_punc(d)

/usr/local/lib/python3.10/dist-packages/spacy/pipeline/lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)


In [127]:
tokens[:10]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long']

In [83]:
len(tokens)

11338

In [84]:
#25 words --predict--> #20 words
train_len = 25 + 1

text_sequences = []

for i in range(train_len,len(tokens)):
  seq = tokens[i-train_len:i]

  text_sequences.append(seq)

In [85]:
type(text_sequences )

list

In [86]:
text_sequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on']

In [87]:
text_sequences[1]

['me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore']

In [88]:
len(text_sequences[0])

26

In [89]:
print(' '.join(text_sequences[0]))
print('\n')
print(' '.join(text_sequences[1]))

call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on


me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore


In [90]:
from keras.preprocessing.text import Tokenizer

In [93]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [94]:
#Assign an id to each of word
sequences[0]

[956,
 14,
 263,
 51,
 261,
 408,
 87,
 219,
 129,
 111,
 954,
 260,
 50,
 43,
 38,
 314,
 7,
 23,
 546,
 3,
 150,
 259,
 6,
 2713,
 14,
 24]

In [126]:
tokenizer.index_word

{1: 'the',
 2: 'a',
 3: 'and',
 4: 'of',
 5: 'i',
 6: 'to',
 7: 'in',
 8: 'it',
 9: 'that',
 10: 'he',
 11: 'his',
 12: 'was',
 13: 'but',
 14: 'me',
 15: 'with',
 16: 'as',
 17: 'at',
 18: 'this',
 19: 'you',
 20: 'is',
 21: 'all',
 22: 'for',
 23: 'my',
 24: 'on',
 25: 'be',
 26: "'s",
 27: 'not',
 28: 'from',
 29: 'there',
 30: 'one',
 31: 'up',
 32: 'what',
 33: 'him',
 34: 'so',
 35: 'bed',
 36: 'now',
 37: 'about',
 38: 'no',
 39: 'into',
 40: 'by',
 41: 'were',
 42: 'out',
 43: 'or',
 44: 'harpooneer',
 45: 'had',
 46: 'then',
 47: 'have',
 48: 'an',
 49: 'upon',
 50: 'little',
 51: 'some',
 52: 'old',
 53: 'like',
 54: 'if',
 55: 'they',
 56: 'would',
 57: 'do',
 58: 'over',
 59: 'landlord',
 60: 'thought',
 61: 'room',
 62: 'when',
 63: 'could',
 64: "n't",
 65: 'night',
 66: 'here',
 67: 'head',
 68: 'such',
 69: 'which',
 70: 'man',
 71: 'did',
 72: 'sea',
 73: 'time',
 74: 'other',
 75: 'very',
 76: 'go',
 77: 'these',
 78: 'more',
 79: 'though',
 80: 'first',
 81: 'sort',


In [103]:
for i in sequences[0]:
  print(f"{i:<4} : {tokenizer.index_word[i]}")

956  : call
14   : me
263  : ishmael
51   : some
261  : years
408  : ago
87   : never
219  : mind
129  : how
111  : long
954  : precisely
260  : having
50   : little
43   : or
38   : no
314  : money
7    : in
23   : my
546  : purse
3    : and
150  : nothing
259  : particular
6    : to
2713 : interest
14   : me
24   : on


In [108]:
type(tokenizer.word_counts)

collections.OrderedDict

In [124]:
tokenizer.word_counts

OrderedDict([('call', 27),
             ('me', 2471),
             ('ishmael', 133),
             ('some', 758),
             ('years', 135),
             ('ago', 84),
             ('never', 449),
             ('mind', 164),
             ('how', 321),
             ('long', 374),
             ('precisely', 37),
             ('having', 142),
             ('little', 767),
             ('or', 950),
             ('no', 1003),
             ('money', 120),
             ('in', 5647),
             ('my', 1786),
             ('purse', 71),
             ('and', 9646),
             ('nothing', 281),
             ('particular', 152),
             ('to', 6497),
             ('interest', 24),
             ('on', 1716),
             ('shore', 26),
             ('i', 7150),
             ('thought', 676),
             ('would', 702),
             ('sail', 104),
             ('about', 1014),
             ('a', 10377),
             ('see', 416),
             ('the', 15540),
             ('watery', 26),
  

In [121]:
# Get word counts
word_counts = tokenizer.word_counts

# Sort word counts in descending order
sorted_word_counts = sorted(word_counts.items(), key=lambda x: -x[1])

# Print sorted word counts
for word, count in sorted_word_counts[:10]:
    print(f"{word:<15}: {count}")

the            : 15540
a              : 10377
and            : 9646
of             : 8287
i              : 7150
to             : 6497
in             : 5647
it             : 4238
that           : 3770
he             : 3247


In [114]:
vocabulary_size = len(tokenizer.word_counts)

In [115]:
vocabulary_size

2718

In [117]:
type(sequences)

list

In [119]:
import numpy as np
sequences = np.array(sequences)

In [120]:
print(sequences)

[[ 956   14  263 ... 2713   14   24]
 [  14  263   51 ...   14   24  957]
 [ 263   51  261 ...   24  957    5]
 ...
 [ 952   12  166 ...  262   53    2]
 [  12  166 2712 ...   53    2 2718]
 [ 166 2712    3 ...    2 2718   26]]
